// Reproducible bilingual introduction. HTML remains the editable PDF source.
import {readFileSync, writeFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import {resolve, dirname} from 'node:path';
const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '../..');
const minimal = readFileSync(resolve(root, 'tests/docs/minimal.zig'), 'utf8');
const code = minimal.slice(minimal.indexOf('fn hello()'), minimal.indexOf('pub fn main')).trim();
const evidence = JSON.parse(readFileSync(resolve(root, 'docs/evidence/public-presentation/threaded-main.json')));
const rates = ['hello','echo','db'].map(name => {
  const runs = evidence.runs.filter(run => run.endpoint === name);
  return runs.reduce((sum, run) => sum + Number(run.oha.statusCodeDistribution['200']) / run.oha.summary.total, 0) / runs.length;
});
const escape = value => String(value).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');
const highlight = value => escape(value).replace(/("[^"\n]*")|\b(fn|pub|const|return|var|try|defer)\b/g, (match,string) => `<span class="${string?'str':'kw'}">${match}</span>`);
const pre = value => `<pre>${highlight(value)}</pre>`;
const link = (lang, page, label) => `<a href="https://github.com/moribit/Akamata/blob/main/docs/${lang}/${page}">${label}</a>`;
const css = `@page{size:13.333in 7.5in;margin:0}*{box-sizing:border-box}body{margin:0;color:#edf5ed;background:#07120f;font:28px/1.45 "Hiragino Sans","Noto Sans CJK JP",Arial,sans-serif;-webkit-print-color-adjust:exact;print-color-adjust:exact}.slide{width:1280px;height:720px;padding:66px 76px 60px;position:relative;break-after:page;overflow:hidden;background:#07120f}.slide:last-child{break-after:auto}h1{font-size:88px;line-height:1.05;margin:30px 0;color:#f1b75b}h2{font-size:48px;line-height:1.2;color:#f1b75b;margin:0 0 36px}p{margin:20px 0}.lead{font-size:36px;max-width:990px}.small{font-size:20px;color:#b7cabb}.note{font-size:20px;color:#b7cabb;position:absolute;bottom:66px;left:76px;right:76px}.page{position:absolute;right:40px;bottom:24px;color:#8ca99a;font-size:15px}.eyebrow{font-size:20px;letter-spacing:2px;color:#8ed39d}.hero{background:#07120f url('../../assets/branding/akamata-ascii-hero.png') right center/cover no-repeat}.hero:before{content:"";position:absolute;inset:0;background:linear-gradient(90deg,rgba(7,18,15,.99),rgba(7,18,15,.94) 42%,rgba(7,18,15,.25))}.hero>*{position:relative}.hero>.page{position:absolute}.hero .lead{max-width:700px}pre{font:28px/1.5 Menlo,"DejaVu Sans Mono",monospace;margin:20px 0;white-space:pre;padding:0;color:#e8ede9}.kw{color:#8ed39d}.str{color:#f5d99c}a{color:#8ed39d;text-decoration:underline;text-underline-offset:5px}.diagram{display:grid;grid-template-columns:1fr 1fr;column-gap:90px;margin-top:28px;text-align:center}.root{grid-column:1/-1;margin-bottom:24px;color:#f5d99c;font-size:34px}.branch{border-top:2px solid #557761;padding-top:20px}.branch h3{margin:0 0 12px;color:#8ed39d;font-size:30px}.branch p{margin:4px 0}.sequence{display:flex;align-items:flex-start;gap:22px;margin-top:64px}.sequence>div{flex:1;min-width:0;border-top:2px solid #557761;padding-top:20px}.sequence strong{display:block;color:#8ed39d;font-size:30px}.sequence span{font-size:21px;display:block;margin-top:12px}.growth{display:grid;grid-template-columns:1fr 1fr;gap:22px 80px;font-size:31px}.growth div{border-bottom:1px solid #365240;padding-bottom:12px}.growth b{color:#8ed39d;margin-right:16px}.metrics{display:flex;gap:65px;margin-top:65px}.metrics>div{flex:1}.metrics strong{font-size:66px;color:#f5d99c;display:block}.metrics span{display:block;margin-top:12px}.flow{display:flex;gap:28px;flex-wrap:wrap;margin-top:45px}.flow span{font-size:28px;border-top:2px solid #557761;padding-top:16px}table{width:100%;border-collapse:collapse;font-size:23px;margin-top:18px}th{text-align:left;color:#8ed39d}th,td{padding:12px 10px;border-bottom:1px solid #365240}td:first-child{color:#f5d99c}.links{display:flex;gap:42px;margin-top:28px}.aside{font-size:26px;color:#c6dbc9;max-width:960px}`;
for (const lang of ['en','ja']) {
  const ja = lang==='ja';
  const t = (en,jp) => ja?jp:en;
  const slides=[];
  const add=(title,body,options={})=>slides.push(`<section class="slide ${options.hero?'hero':''}">${title?`<h2>${title}</h2>`:''}${body}${options.note?`<div class="note">${options.note}</div>`:''}<span class="page">${String(slides.length+1).padStart(2,'0')}</span></section>`);
  add('', `<div class="eyebrow">NATIVE + CLOUDFLARE WORKERS</div><h1>Akamata</h1><p class="lead">Portable Zig<br>Backend Framework</p><p class="aside">${t('Zig functions. Typed APIs. Explicit ownership.','普通のZig関数から、型付きWeb APIへ。')}</p>`, {hero:true});
  add(t('The application is yours','Zigで書くアプリケーション'), `<p class="lead">${t('Write Zig. Build a backend.<br>Choose Native or Cloudflare Workers.','Zigでbackendを作る。<br>NativeかCloudflare Workersを選ぶ。')}</p><div class="diagram"><div class="root">Application</div><div class="branch"><h3>Native</h3><p>VPS / local / Container</p></div><div class="branch"><h3>Cloudflare Workers</h3><p>WASM / Edge</p></div></div>`);
  add(t('An ordinary function becomes an API','普通の関数がWeb APIになる'),pre(code),{note:t('Application declaration from tests/docs/minimal.zig. Allocator and entry point omitted.','tests/docs/minimal.zigのApplication宣言。allocatorとentry pointは省略。')});
  add(t('Zig types define the HTTP contract','Zigの型をHTTP contractへ'),`<div class="diagram"><div class="root">Zig function + struct + error set</div><div class="branch"><h3>${t('Explicit inputs','明示的な入力')}</h3><p>Path / Query / Header / Cookie</p><p>JSON DTO / Validation / Principal</p></div><div class="branch"><h3>${t('Typed results','型付きの結果')}</h3><p>Response / HTTP error mapping</p><p>Security / Capability metadata</p></div><div class="root" style="margin-top:35px;margin-bottom:0">Router / OpenAPI / TypeScript client / Tests</div></div>`,{note:t('Handlers and explicit endpoint metadata share the existing HTTP core.','handlerと明示endpoint metadataを、既存HTTP coreで共有。')});
  add(t('Room to grow','小さなAPIから実アプリケーションへ'),`<div class="growth">${['Function','Typed JSON API','Database','Authentication','Storage / Queue','Realtime'].map((name,i)=>`<div><b>0${i+1}</b>${name}</div>`).join('')}</div><p class="aside" style="margin-top:50px">${t('Start without Context. Use explicit Context, middleware and provider owners when you need control.','最初はContextなしで開始。必要になればContext、middleware、provider ownerへ降りられます。')}</p>`);
  add(t('One application, explicit providers','共通applicationと、明示的なprovider'),`<div class="diagram"><div class="root">Application / Portable Contract</div><div class="branch"><h3>Native</h3><p>SQLite / Turso</p><p>Filesystem</p><p>jobs.Queue</p><p>Native realtime Service</p></div><div class="branch"><h3>Workers</h3><p>D1 / Turso</p><p>R2</p><p>Queues</p><p>Durable Objects gateway</p></div></div>`,{note:t('Container uses Native providers. Entry points, owners and platform limits remain explicit.','ContainerはNative providerを利用。entry point・owner・platform制限は明示します。')});
  add(t('Native Threaded performance','Native Threadedの測定結果'),`<div class="metrics">${rates.map((rate,i)=>`<div><strong>${(rate/1000).toFixed(0)}k</strong><span>${['/hello','/echo','/db/1'][i]}</span><span class="small">HTTP 200 req/s</span></div>`).join('')}</div><p class="aside" style="margin-top:45px">${t('A local runtime snapshot. No ranking or cross-framework comparison.','ローカルruntimeの測定値。他frameworkとの順位・比較を示すものではありません。')}</p>`,{note:`macOS 27 / Apple M2 / Zig 0.17.0 / ReleaseFast / Threaded<br>32 keep-alive / loopback / oha ${escape(evidence.oha_version.replace('oha ',''))} / 3 × 3s per workload / ${t('mean of all rounds','全roundの平均')}<br>${link(lang,'public-performance.md',t('Raw data, commit/binary SHA and reproduction','raw data・commit/binary SHA・再現手順'))}`});
  add(t('The same domain code at the edge','domain codeをEdgeへ'),`<p class="lead">Workers WASM + managed JavaScript glue</p><div class="flow"><span>D1</span><span>R2</span><span>Queues</span><span>Durable Objects</span></div><p class="aside" style="margin-top:45px">${t('Share DTOs, error meanings, event protocols and portable service effects. Configure bindings and owners for the target.','DTO・errorの意味・event protocol・portable serviceのeffectsを共有。targetに合わせてbindingとownerを設定します。')}</p>`,{note:link(lang,'deployment-validation.md',t('Offline adapter/host contracts are tested. Live Cloudflare certification is not claimed.','adapter/host contractはoffline検証。live Cloudflare認証済みとは主張しません。'))});
  add(t('Test the application in process','socketなしのapplication test'),pre(`var client = app.client(allocator);
var response = try client.post("/users")
    .json(.{ .name = "Alice" }).send();
defer response.deinit();
try response.expectStatus(.created);`)+`<p class="aside">MemoryStore / QueueRecorder / Principal injection</p>`,{note:t('The shared DX fixture runs on Native and Workers WASM. Test doubles do not prove live delivery.','共通DX fixtureをNative / Workers WASMで実行。fake providerはlive deliveryの証明ではありません。')});
  add(t('The development workflow','開発の流れ'),`<div class="sequence">${[['init',t('Minimal app','最小app')],['dev',t('Build / run / watch','build / run / watch')],['test',t('Application tests','appをテスト')],['check',t('Project validation','projectを検証')],['deploy',t('Explicit target','targetを明示')]].map(([cmd,description])=>`<div><strong>${cmd}</strong><span>${description}</span></div>`).join('')}</div><p class="lead" style="margin-top:55px">akamata init myapp</p><p class="aside">${t('Inspect routes, OpenAPI and capabilities as the application grows.','appの成長に合わせてroutes・OpenAPI・capabilitiesを確認。')}</p>`,{note:t('Commands require project configuration. Deployment does not implicitly create resources.','commandはproject設定を利用。deployはresourceを暗黙作成しません。')});
  add(t('Portability reaches deployment','deploymentまで追跡するPortable Contract'),`<div class="flow">${['Application','Capability','Provider','Binding','Owner','Deployment'].map(s=>`<span>${s}</span>`).join('')}</div><p class="lead" style="margin-top:55px">${t('Declare what the app needs.<br>Validate how the target provides it.','必要な機能を宣言。<br>targetがどう提供するかを検証。')}</p>`,{note:link(lang,'deployment-validation.md',t('Local validation, remote reachability and application readiness are different evidence levels.','local validation・remote reachability・application readinessは異なる証拠レベルです。'))});
  add(t('What runs where','Native / Workers / Containerの対応'),`<table><thead><tr><th></th><th>Native</th><th>Workers</th><th>Container</th></tr></thead><tbody><tr><td>HTTP</td><td>Threaded</td><td>WASM / fetch</td><td>Threaded</td></tr><tr><td>DB</td><td>SQLite / Turso</td><td>D1 / Turso</td><td>SQLite / Turso</td></tr><tr><td>Storage</td><td>Filesystem</td><td>R2</td><td>Filesystem *</td></tr><tr><td>Queue</td><td>jobs.Queue</td><td>Queues</td><td>jobs.Queue</td></tr><tr><td>Realtime</td><td>Native Service</td><td>DO gateway</td><td>Native Service</td></tr></tbody></table>`,{note:t('* Persistent DB/filesystem need mounted volumes. Streaming, retry and gateway details differ by platform.','* DB/filesystemの永続化にはvolumeが必要。streaming・retry・gatewayの詳細はplatformで異なります。')});
  add(t('Your first application','最初のアプリケーション'),pre(`akamata init myapp
cd myapp
akamata dev`)+`<div class="links">${link(lang,'quickstart.md','Getting Started')}${link(lang,'README.md','Guides / Examples')}<a href="https://github.com/moribit/Akamata">GitHub</a></div><p class="small">${t('Install the CLI first. Use Zig 0.17 and the v0.2.0 dependency; see Getting Started.','先にCLIをinstall。Zig 0.17とv0.2.0 dependencyを使用。Getting Startedへ。')}</p>`,{hero:true});
  writeFileSync(resolve(here,ja?'slides.ja.html':'slides.html'),`<!doctype html><html lang="${lang}"><head><meta charset="utf-8"><title>Akamata - Portable Zig Backend Framework</title><style>${css}</style></head><body>${slides.join('\n')}</body></html>\n`);
}
