// {{NAME}} — generated by `akamata init {{NAME}}`.
//
// One file is enough to demo the modern model + handler workflow. Move things
// into separate files (models.zig, handlers.zig, setup.zig) as the app grows.

const std = @import("std");
const am = @import("akamata");

// ===== Model =====================================================
//
// Define a struct with a `__schema` block to get a typed table + a Repo with
// `.find / .all / .where / .create / .save / .delete`. See docs/en/handbook.md
// for indexes, defaults, validators, and relations.

pub const Note = struct {
    id: ?i64 = null,
    title: []const u8,
    body: []const u8,
    created_at: ?i64 = null,

    pub const __schema = .{
        .table = "notes",
        .primary_key = "id",
        .defaults = .{
            .created_at = "unixepoch()",
        },
        .validates = .{
            .title = .{ am.model.rule.required, am.model.rule.max_len(120) },
            .body = .{ am.model.rule.required, am.model.rule.max_len(4096) },
        },
    };
};

const Notes = am.model.repo(Note);

// ===== App state =================================================
//
// `db` is special-cased by `c.db()` (and `c.cfg()` if you add config). The
// model-aware migrator walks `all_models` to keep the schema in sync.

pub const State = struct {
    // Older pinned releases still compile; upgrade the dependency to enable
    // the portable application contract and its tooling protocol.
    pub const application_contract = if (@hasDecl(Portable, "For")) Portable.For(if (am.backend == .workers) .workers else .native) else void;
    db: am.db.Db,
};

const Portable = if (@hasDecl(am.capability, "Application")) struct {
    const DatabaseBinding = am.binding.D1("DB");
    pub fn For(comptime target: am.capability.Target) type {
        const C = am.capability.Contract("{{NAME}}", &.{.database}, &.{.{
            .capability = .database,
            .provider = am.capability.defaultProvider(.database, target),
            .binding = if (target == .workers) DatabaseBinding.binding_name else null,
        }});
        comptime if (target == .workers) am.binding.validateContract(struct { db: DatabaseBinding }, C, target) else C.validate(target);
        return C;
    }
    fn database(comptime method: am.Method, comptime path: []const u8, comptime handler: anytype, comptime operation: []const u8) type {
        return am.capability.Uses(am.contract.Endpoint(method, path, handler, .{ .operation_id = operation }), &.{.database});
    }
    pub const endpoints = .{
        am.contract.Endpoint(.GET, "/", index, .{ .operation_id = "index" }),
        database(.GET, "/health", health, "health"),
        database(.GET, "/notes", listNotes, "listNotes"),
        database(.POST, "/notes", createNote, "createNote"),
        database(.GET, "/notes/:id", showNote, "showNote"),
        database(.DELETE, "/notes/:id", deleteNote, "deleteNote"),
    };
} else struct {};

pub const all_models = [_]am.model.TableDef{
    am.model.tableDef(Note),
};

// ===== Handlers ==================================================

const Ctx = am.Context(State);

fn index(c: *Ctx) !void {
    try c.json(.{
        .name = "{{NAME}}",
        .endpoints = .{
            .health = "GET /health",
            .list = "GET /notes",
            .create = "POST /notes  { title, body }",
            .show = "GET /notes/:id",
            .delete = "DELETE /notes/:id",
        },
    }, 200);
}

fn health(c: *Ctx) !void {
    var stmt = c.db().prepare("SELECT 1") catch return c.serverError("db unavailable");
    defer stmt.deinit();
    _ = stmt.step() catch return c.serverError("db unavailable");
    try c.json(.{ .status = "ok" }, 200);
}

fn listNotes(c: *Ctx) !void {
    const notes = try Notes.all(c.db(), c.arena);
    try c.json(.{ .notes = notes }, 200);
}

fn createNote(c: *Ctx) !void {
    const note = (try c.input(Note)) orelse return;
    const created = try Notes.create(c.db(), c.arena, note);
    try c.json(created, 201);
}

fn showNote(c: *Ctx) !void {
    const id = c.req.paramAs(i64, "id") catch return c.badRequest("invalid id");
    const n = (try Notes.find(c.db(), c.arena, id)) orelse return c.notFound();
    try c.json(n, 200);
}

fn deleteNote(c: *Ctx) !void {
    const id = c.req.paramAs(i64, "id") catch return c.badRequest("invalid id");
    try Notes.delete(c.db(), id);
    try c.json(.{ .deleted = id }, 200);
}

// ===== Wiring ====================================================

pub fn registerRoutes(app: *am.App(State)) !void {
    _ = try app.useAll(am.mw.recover(State));
    _ = try app.useAll(am.mw.logger(State));

    if (comptime @hasDecl(Portable, "endpoints")) {
        inline for (Portable.endpoints) |Endpoint| try Endpoint.register(app);
    } else {
        _ = try app.get("/", index);
        _ = try app.get("/health", health);
        _ = try app.get("/notes", listNotes);
        _ = try app.post("/notes", createNote);
        _ = try app.get("/notes/:id", showNote);
        _ = try app.delete("/notes/:id", deleteNote);
    }
}

pub fn buildState(alloc: std.mem.Allocator) !State {
    if (am.backend == .native) am.env.loadDotEnv(alloc, ".env") catch {};
    const url = am.env.get(alloc, "DATABASE_URL") orelse
        try alloc.dupe(u8, if (am.backend == .native) "file:{{NAME}}.db" else "d1:DB");
    defer alloc.free(url);
    const database = try am.db.open(alloc, url);
    if (am.backend == .native) {
        var arena_state: std.heap.ArenaAllocator = .init(alloc);
        defer arena_state.deinit();
        const plan = am.model.migrate.diff(arena_state.allocator(), database, &all_models) catch |e| {
            std.log.warn("migrate.diff: {t}", .{e});
            return .{ .db = database };
        };
        am.model.migrate.apply(arena_state.allocator(), database, plan) catch |e| {
            std.log.warn("migrate.apply: {t}", .{e});
        };
    }
    return .{ .db = database };
}

fn migrateCommand(alloc: std.mem.Allocator, mode: []const u8, args: []const [:0]const u8) !void {
    var dir: []const u8 = "migrations";
    var target: ?[]const u8 = null;
    for (args) |raw| {
        const arg = std.mem.sliceTo(raw, 0);
        if (std.mem.startsWith(u8, arg, "--dir=")) dir = arg[6..] else if (std.mem.startsWith(u8, arg, "--target=")) target = arg[9..] else {
            std.debug.print("{s}: unknown option `{s}`\n", .{ mode, arg });
            return error.InvalidMigrationOption;
        }
    }

    am.env.loadDotEnv(alloc, ".env") catch {};
    const url = am.env.get(alloc, "DATABASE_URL") orelse try alloc.dupe(u8, "file:{{NAME}}.db");
    defer alloc.free(url);

    var arena_state: std.heap.ArenaAllocator = .init(alloc);
    defer arena_state.deinit();
    const arena = arena_state.allocator();
    const database = try am.db.open(alloc, url);
    defer database.close();

    const all = am.model.migrate.loadMigrationsFromDir(arena, dir) catch |err| {
        if (err == error.MigrationsDirNotFound) {
            std.debug.print("migrate-up: directory `{s}` does not exist\n", .{dir});
        }
        return err;
    };
    const migrator: am.model.migrate.Migrator = .{ .arena = arena, .db = database };
    const pending = try migrator.pending(all);

    if (std.mem.eql(u8, mode, "migrate-status")) {
        const applied = try migrator.appliedVersions();
        for (all) |migration| {
            var done = false;
            for (applied) |version| if (std.mem.eql(u8, version, migration.version)) {
                done = true;
            };
            std.debug.print("{s} {s}\n", .{ if (done) "up  " else "down", migration.name });
        }
        return;
    }
    if (std.mem.eql(u8, mode, "migrate-plan")) {
        for (pending) |migration| std.debug.print("apply {s}\n", .{migration.name});
        if (pending.len == 0) std.debug.print("nothing pending\n", .{});
        return;
    }
    if (std.mem.eql(u8, mode, "migrate-rollback") or std.mem.eql(u8, mode, "migrate-redo")) {
        if (comptime @hasDecl(am.model.migrate.Migrator, "rollbackLast")) {
            const rolled_back = try migrator.rollbackLast(all);
            if (rolled_back == null) {
                std.debug.print("nothing to roll back\n", .{});
                return;
            }
            std.debug.print("rolled back {s}\n", .{rolled_back.?.name});
            if (std.mem.eql(u8, mode, "migrate-rollback")) return;
            try migrator.applyAll(&.{rolled_back.?});
            std.debug.print("reapplied {s}\n", .{rolled_back.?.name});
            return;
        } else {
            std.debug.print("rollback requires a newer Akamata revision; update the dependency first\n", .{});
            return error.FrameworkUpgradeRequired;
        }
    }

    var selected: std.ArrayList(am.model.migrate.Migration) = .empty;
    for (pending) |migration| {
        if (target) |limit| {
            if (std.mem.order(u8, migration.version, limit) == .gt) continue;
        }
        try selected.append(arena, migration);
    }
    if (selected.items.len == 0) {
        std.log.info("migrate-up: nothing pending ({d} migration file(s))", .{all.len});
        return;
    }
    for (selected.items) |migration| std.log.info("applying {s}", .{migration.name});
    try migrator.applyAll(selected.items);
    std.log.info("applied {d} migration(s)", .{selected.items.len});
}

/// Application management commands invoked by `akamata runner <name>`.
/// Add branches here; arguments arrive without the protocol prefix.
fn runnerCommand(app: *am.App(State), args: []const [:0]const u8) !void {
    if (args.len == 0) return error.MissingRunnerCommand;
    const name = std.mem.sliceTo(args[0], 0);
    if (std.mem.eql(u8, name, "db-check")) {
        var stmt = try app.state().db.prepare("SELECT 1");
        defer stmt.deinit();
        _ = try stmt.step();
        std.debug.print("database: ok\n", .{});
        return;
    }
    std.debug.print("unknown application command: {s}\n", .{name});
    return error.UnknownRunnerCommand;
}

pub fn main(init: std.process.Init) !void {
    var gpa: std.heap.DebugAllocator(.{}) = .init;
    defer _ = gpa.deinit();
    const alloc = gpa.allocator();

    var args_arena: std.heap.ArenaAllocator = .init(alloc);
    defer args_arena.deinit();
    const args = try init.minimal.args.toSlice(args_arena.allocator());
    // Metadata tooling runs before resource initialization/migration.
    if (args.len >= 2 and std.mem.eql(u8, std.mem.sliceTo(args[1], 0), "akamata-capabilities")) {
        if (comptime !@hasDecl(Portable, "For")) {
            std.debug.print("capability inspection requires a newer Akamata dependency\n", .{});
            return error.FrameworkUpgradeRequired;
        } else {
            const target = if (args.len == 3) std.mem.sliceTo(args[2], 0) else "native";
            var stdout_buffer: [4096]u8 = undefined;
            var stdout = std.Io.File.stdout().writer(init.io, &stdout_buffer);
            if (std.mem.eql(u8, target, "native")) {
                try Portable.For(.native).writeManifest(.native, &stdout.interface, Portable.endpoints);
            } else if (std.mem.eql(u8, target, "workers")) {
                try Portable.For(.workers).writeManifest(.workers, &stdout.interface, Portable.endpoints);
            } else if (std.mem.eql(u8, target, "containers")) {
                try Portable.For(.containers).writeManifest(.containers, &stdout.interface, Portable.endpoints);
            } else return error.InvalidTarget;
            return stdout.interface.flush();
        }
    }
    const migrate_up_mode = "migrate-up";
    _ = migrate_up_mode; // documents the runner contract used by the CLI
    if (args.len >= 2 and std.mem.startsWith(u8, std.mem.sliceTo(args[1], 0), "migrate-")) {
        return migrateCommand(alloc, std.mem.sliceTo(args[1], 0), args[2..]);
    }

    const state = try buildState(alloc);
    defer state.db.close();
    var app = am.App(State).init(alloc, state);
    defer app.deinit();
    try registerRoutes(&app);

    if (args.len >= 2 and std.mem.eql(u8, std.mem.sliceTo(args[1], 0), "akamata-runner")) {
        return runnerCommand(&app, args[2..]);
    }

    // Local tooling protocol: lets `akamata client --tui` inspect every
    // registered route without exposing an OpenAPI endpoint over HTTP.
    if (args.len >= 2 and std.mem.eql(u8, std.mem.sliceTo(args[1], 0), "akamata-openapi")) {
        const spec = try am.openapi.generate(@TypeOf(app), &app, alloc, .{
            .title = "{{NAME}} API",
            .version = "0.0.1",
        });
        defer alloc.free(spec);
        var stdout_buffer: [4096]u8 = undefined;
        const io = std.Io.Threaded.global_single_threaded.io();
        var stdout = std.Io.File.stdout().writer(io, &stdout_buffer);
        try stdout.interface.writeAll(spec);
        try stdout.interface.writeByte('\n');
        return stdout.interface.flush();
    }

    const port_env = am.env.get(alloc, "PORT");
    defer if (port_env) |p| alloc.free(p);
    const port: u16 = if (port_env) |p| std.fmt.parseInt(u16, p, 10) catch 8080 else 8080;

    std.log.info("{{NAME}} listening on :{d}", .{port});
    try app.serve(.{ .port = port });
}
