const std = @import("std");
const am = @import("akamata");
const application = @import("application.zig");
const contracts = @import("contracts.zig");

test "reference production owners deliver queued reports and clean test effects" {
    const allocator = std.testing.allocator;
    const C = contracts.For(.native);
    const database = try am.db.openForContract(allocator, C, "file::memory:");
    defer database.close();
    try application.ensureSchema(database);
    var directory = std.testing.tmpDir(.{});
    defer directory.cleanup();
    var storage = try am.StorageFactory.initForContract(allocator, C, .{ .native_io = std.testing.io, .native_root = directory.dir });
    var realtime = am.realtime.Native.initForContract(allocator, C);
    defer realtime.deinit();
    var effects: application.ReportEffects = .{ .db = database };
    const owner = try am.jobs.Provider(contracts.ReportDescriptor).createForContract(allocator, C, database, .{ .context = &effects, .handler_with_context = application.consumeReport }, .{});
    defer owner.deinit();
    var app = am.App(application.State).init(allocator, .{ .db = database, .store = storage.store(), .queue = owner.producer(), .realtime = realtime.service(), .jwt_secret = "contract-secret", .login_secret = "login-secret", .schema_ready = true });
    defer app.deinit();
    try application.register(&app);
    var client = am.testing.Client(@TypeOf(app)).init(allocator, &app);
    var login = try client.post("/login").json(.{ .subject = "contract-user", .credential = "login-secret" }).send();
    defer login.deinit();
    try login.expectStatus(200);
    const token = try login.json(struct { access_token: []const u8 });
    const authorization = try std.fmt.allocPrint(allocator, "Bearer {s}", .{token.access_token});
    defer allocator.free(authorization);
    var report = try client.post("/reports").header("authorization", authorization).json(.{ .firmware_version = "contract", .uptime_seconds = 1 }).send();
    defer report.deinit();
    try report.expectStatus(201);
    const created = try report.json(struct { id: u64 });
    const path = try std.fmt.allocPrint(allocator, "/reports/{d}/delivery", .{created.id});
    defer allocator.free(path);
    var pending = try client.get(path).header("authorization", authorization).send();
    defer pending.deinit();
    try pending.expectStatus(200);
    try std.testing.expect(!(try pending.json(struct { delivered: bool })).delivered);
    var worker = owner.worker();
    try worker.tick();
    var delivered = try client.get(path).header("authorization", authorization).send();
    defer delivered.deinit();
    try delivered.expectStatus(200);
    const result = try delivered.json(struct { delivered: bool, attempt: u16 });
    try std.testing.expect(result.delivered and result.attempt == 1);
    const delete_path = try std.fmt.allocPrint(allocator, "/reports/{d}", .{created.id});
    defer allocator.free(delete_path);
    var removed = try client.request(.DELETE, delete_path).header("authorization", authorization).send();
    defer removed.deinit();
    try removed.expectStatus(204);
    owner.stop();
}
