//! Type-safe client generation from app route metadata.
//!
//! Walks the same `app.routes[i].meta` chain that `openapi.zig` uses and
//! emits a runnable TypeScript client module. The legacy Zig enum value is
//! retained for source compatibility but fails generation until its transport
//! and lifetime contract is complete.
//!
//!   * **TypeScript** (`.typescript`) — one async function per documented
//!     endpoint, fetch-based, with TS interfaces for every request/response
//!     type.
//!
//! Routes registered via the bare `app.get/post/...` helpers (no meta) are
//! included with untyped schemas; `endpoint` routes add reflected schemas.

const std = @import("std");
const openapi = @import("openapi.zig");

pub const Target = enum {
    typescript,
    zig,
};

pub const Options = struct {
    target: Target,
    /// Base URL used in the generated client. Can be overridden by a
    /// runtime argument at the call site.
    base_url: []const u8 = "",
};

pub fn generate(comptime AppT: type, app: *AppT, gpa: std.mem.Allocator, opts: Options) ![]u8 {
    var arena_state: std.heap.ArenaAllocator = .init(gpa);
    defer arena_state.deinit();
    const arena = arena_state.allocator();

    // Reuse the OpenAPI schema collector so types are emitted exactly once.
    var builder: openapi.SpecBuilder = .init(arena);

    var ops: std.ArrayList(OpEntry) = .empty;
    const route_views = try app.routeViews(arena);
    for (route_views) |r| {
        if (r.kind != .http) continue;
        const meta = r.meta orelse @import("openapi.zig").Spec(.{});
        const refs = try meta.schema_fn(arena, &builder);
        try ops.append(arena, .{
            .method = r.method,
            .raw_path = r.path,
            .meta = meta,
            .refs = refs,
        });
    }

    var names = std.StringHashMap(void).init(arena);
    for (ops.items) |op| {
        var name_writer: std.Io.Writer.Allocating = .init(arena);
        try writeOperationFnName(&name_writer.writer, op.method, op.raw_path);
        const name = name_writer.writer.buffered();
        if (names.contains(name)) return error.DuplicateClientOperationName;
        try names.put(name, {});
    }

    var aw: std.Io.Writer.Allocating = try .initCapacity(arena, 4096);
    const w = &aw.writer;

    switch (opts.target) {
        .typescript => try emitTypescript(w, opts.base_url, ops.items, &builder),
        .zig => return error.UnsupportedTarget,
    }
    return gpa.dupe(u8, aw.written());
}

const OpEntry = struct {
    method: @import("http/request.zig").Method,
    raw_path: []const u8,
    meta: *const openapi.EndpointMeta,
    refs: openapi.EndpointMeta.Refs,
};

// =========================================================================
// TypeScript emitter
// =========================================================================

fn emitTypescript(
    w: *std.Io.Writer,
    base_url: []const u8,
    ops: []const OpEntry,
    builder: *openapi.SpecBuilder,
) !void {
    try w.writeAll(
        \\// Generated by Akamata client_gen. Do not edit by hand.
        \\
        \\
    );
    try w.print("const DEFAULT_BASE = {f};\n\n", .{jsonString(base_url)});
    try w.writeAll(
        \\export class HttpError<Body = unknown> extends Error {
        \\  constructor(public readonly status: number, public readonly body: Body, detail: string) {
        \\    super(`HTTP ${status}${detail ? `: ${detail}` : ""}`);
        \\    this.name = "HttpError";
        \\  }
        \\}
        \\
    );
    for (ops) |op| {
        var count: usize = 0;
        for (op.meta.additional_responses) |response| count += response.error_kinds.len;
        if (count == 0) continue;
        try w.writeAll("export type ");
        try writeOperationFnName(w, op.method, op.raw_path);
        try w.writeAll("Error = ");
        var emitted = false;
        for (op.meta.additional_responses) |response| for (response.error_kinds) |kind| {
            if (emitted) try w.writeAll(" | ");
            emitted = true;
            try w.print("{{ status: {d}; body: {{ error_kind: {f} }} }}", .{ response.status, jsonString(kind) });
        };
        try w.writeAll(";\n");
        try w.writeAll("export function is_");
        try writeOperationFnName(w, op.method, op.raw_path);
        try w.writeAll("Error(value: unknown): value is HttpError<");
        try writeOperationFnName(w, op.method, op.raw_path);
        try w.writeAll("Error[\"body\"]> & ");
        try writeOperationFnName(w, op.method, op.raw_path);
        try w.writeAll("Error {\n  return value instanceof HttpError && value.body !== null && typeof value.body === \"object\" && \"error_kind\" in value.body && (\n");
        emitted = false;
        for (op.meta.additional_responses) |response| for (response.error_kinds) |kind| {
            if (emitted) try w.writeAll(" ||\n");
            emitted = true;
            try w.print("    (value.status === {d} && value.body.error_kind === {f})", .{ response.status, jsonString(kind) });
        };
        try w.writeAll("\n  );\n}\n");
    }

    // Type definitions for every collected schema.
    var sch_it = builder.schemas.iterator();
    while (sch_it.next()) |entry| {
        const name = entry.key_ptr.*;
        const json_schema = entry.value_ptr.*;
        if (findField(json_schema, "\"properties\":") != null) {
            try w.print("export interface {s} ", .{name});
            try writeTsInterfaceFromJsonSchema(w, json_schema);
        } else {
            try w.print("export type {s} = ", .{name});
            try writeTsTypeFromJsonSchema(w, json_schema);
            try w.writeAll(";");
        }
        try w.writeAll("\n\n");
    }

    // Client factory.
    try w.writeAll(
        \\export interface ClientOptions {
        \\  baseUrl?: string;
        \\  headers?: Record<string, string>;
        \\  fetch?: typeof fetch;
        \\}
        \\
        \\export function createClient(opts: ClientOptions = {}) {
        \\  const base = opts.baseUrl ?? DEFAULT_BASE;
        \\  const f = opts.fetch ?? globalThis.fetch;
        \\  const baseHeaders = opts.headers ?? {};
        \\  return {
        \\
    );

    for (ops) |op| {
        try emitTypescriptOperation(w, op);
    }

    try w.writeAll(
        \\  };
        \\}
        \\
    );
}

fn emitTypescriptOperation(w: *std.Io.Writer, op: OpEntry) !void {
    try w.writeAll("    ");
    try writeOperationFnName(w, op.method, op.raw_path);
    try w.writeAll(": async (");

    // Path params first.
    var has_path_params = false;
    {
        var seg_it = std.mem.splitScalar(u8, op.raw_path, '/');
        while (seg_it.next()) |seg| {
            if (seg.len > 0 and seg[0] == ':') {
                if (has_path_params) try w.writeAll(", ");
                try w.print("{s}: ", .{seg[1..]});
                if (op.meta.path_ts_type_fn) |render| try render(seg[1..], w) else try w.writeAll("string");
                has_path_params = true;
            }
        }
    }
    // Body if any.
    if (op.refs.request) |req_ref| {
        if (has_path_params) try w.writeAll(", ");
        try w.print("body: {s}", .{refToTypeName(req_ref)});
    }
    // Query params: an inline anonymous interface so callers see the
    // available keys via tooltips. Always optional at the TS level —
    // the OpenAPI spec carries the required-ness.
    const has_query = op.meta.query_ts_fields_fn != null;
    if (has_query) {
        if (has_path_params or op.refs.request != null) try w.writeAll(", ");
        try w.writeAll("query: {\n");
        try op.meta.query_ts_fields_fn.?(w);
        try w.writeAll(if (op.meta.query_required) "    }" else "    } = {}");
    }
    try w.writeAll("): Promise<");
    if (op.refs.response) |res_ref| {
        try w.writeAll(refToTypeName(res_ref));
    } else {
        try w.writeAll(if (op.method == .HEAD or op.meta.success_status == 204 or op.meta.success_status == 205) "void" else "unknown");
    }
    try w.writeAll("> => {\n");

    // Build the path string with template literals for params.
    try w.writeAll("      const path = `");
    {
        var i: usize = 0;
        while (i < op.raw_path.len) {
            if (op.raw_path[i] == ':') {
                const start = i + 1;
                var end = start;
                while (end < op.raw_path.len and op.raw_path[end] != '/') : (end += 1) {}
                try w.print("${{encodeURIComponent(String({s}))}}", .{op.raw_path[start..end]});
                i = end;
            } else {
                try w.writeByte(op.raw_path[i]);
                i += 1;
            }
        }
    }
    try w.writeAll("`;\n");

    if (has_query) {
        // Build the querystring with URLSearchParams, skipping undefined values.
        try w.writeAll(
            \\      const _qs = new URLSearchParams();
            \\      for (const [k, v] of Object.entries(query)) {
            \\        if (v !== undefined && v !== null) _qs.set(k, String(v));
            \\      }
            \\      const _qstr = _qs.toString();
            \\      const _full = `${base}${path}${_qstr ? `?${_qstr}` : ""}`;
            \\
        );
    } else {
        try w.writeAll("      const _full = `${base}${path}`;\n");
    }

    try w.print(
        \\      const res = await f(_full, {{
        \\        method: "{s}",
        \\        headers: {{ ...baseHeaders{s} }},
        \\
    , .{ lowerMethod(op.method), if (op.refs.request != null) ", \"content-type\": \"application/json\"" else "" });
    if (op.refs.request != null) {
        try w.writeAll("        body: JSON.stringify(body),\n");
    }
    try w.writeAll("      });\n");
    try w.writeAll(
        \\      if (!res.ok) {
        \\        const detail = await res.text().catch(() => "");
        \\        let body: unknown = detail;
        \\        try { body = JSON.parse(detail); } catch {}
        \\        throw new HttpError(res.status, body, detail);
        \\      }
        \\
    );
    if (op.refs.response != null) {
        try w.writeAll(if (std.mem.eql(u8, op.meta.response_content_type, "text/plain")) "      return res.text();\n" else "      return res.json();\n");
    } else {
        try w.writeAll("      return;\n");
    }
    try w.writeAll("    },\n");
}

fn writeOperationFnName(w: *std.Io.Writer, method: @import("http/request.zig").Method, path: []const u8) !void {
    // Build a JS identifier from method + path:
    //   GET /users/:id           -> getUsersById
    //   POST /users              -> postUsers
    try w.writeAll(lowerMethod(method));
    var capitalize = true;
    for (path) |c| {
        if (!std.ascii.isAlphanumeric(c) and c != ':') {
            capitalize = true;
            continue;
        }
        if (c == ':') {
            // Convention: ":id" -> "ById"
            try w.writeAll("By");
            capitalize = true;
            continue;
        }
        if (capitalize) {
            try w.writeByte(std.ascii.toUpper(c));
            capitalize = false;
        } else {
            try w.writeByte(c);
        }
    }
}

fn refToTypeName(ref: []const u8) []const u8 {
    // "#/components/schemas/User" -> "User"
    var last_slash: usize = 0;
    for (ref, 0..) |c, i| {
        if (c == '/') last_slash = i + 1;
    }
    return ref[last_slash..];
}

fn lowerMethod(m: @import("http/request.zig").Method) []const u8 {
    return switch (m) {
        .GET => "get",
        .POST => "post",
        .PUT => "put",
        .DELETE => "delete",
        .PATCH => "patch",
        .OPTIONS => "options",
        .HEAD => "head",
    };
}

// Minimal JSON-schema-to-TS-interface converter. The schemas we produce
// have a known shape (writeTypeSchema in openapi.zig); we walk that shape
// directly rather than parsing JSON.
fn writeTsInterfaceFromJsonSchema(w: *std.Io.Writer, schema: []const u8) std.Io.Writer.Error!void {
    // The OpenAPI schemas we emit are top-level `{"type":"object","properties":{...},"required":[...]}`.
    // Reparse that to TS.
    try w.writeAll("{\n");
    // properties section
    if (findField(schema, "\"properties\":")) |props_start| {
        const props_obj = parseObject(schema[props_start..]) orelse {
            try w.writeAll("}");
            return;
        };
        // required list
        var required: []const u8 = "";
        if (findField(schema, "\"required\":")) |req_start| {
            if (parseArray(schema[req_start..])) |arr| required = arr;
        }
        var it = objectFieldsIterator(props_obj);
        while (it.next()) |field| {
            const optional = !arrayContainsString(required, field.name);
            try w.print("  {s}{s}: ", .{ field.name, if (optional) "?" else "" });
            try writeTsTypeFromJsonSchema(w, field.value);
            try w.writeAll(";\n");
        }
    }
    try w.writeAll("}");
}

fn writeTsTypeFromJsonSchema(w: *std.Io.Writer, schema: []const u8) std.Io.Writer.Error!void {
    // Find "type":
    if (findField(schema, "\"type\":")) |t_start| {
        const type_str = parseString(schema[t_start..]) orelse "any";
        if (std.mem.eql(u8, type_str, "string")) {
            try w.writeAll("string");
            return;
        }
        if (std.mem.eql(u8, type_str, "integer") or std.mem.eql(u8, type_str, "number")) {
            try w.writeAll("number");
            return;
        }
        if (std.mem.eql(u8, type_str, "boolean")) {
            try w.writeAll("boolean");
            return;
        }
        if (std.mem.eql(u8, type_str, "null")) {
            try w.writeAll("null");
            return;
        }
        if (std.mem.eql(u8, type_str, "array")) {
            if (findField(schema, "\"items\":")) |i_start| {
                try w.writeAll("Array<");
                try writeTsTypeFromJsonSchema(w, schema[i_start..]);
                try w.writeAll(">");
                return;
            }
            try w.writeAll("Array<any>");
            return;
        }
        if (std.mem.eql(u8, type_str, "object")) {
            try writeTsInterfaceFromJsonSchema(w, schema);
            return;
        }
    }
    // Akamata emits optionals as oneOf(null, T). Preserve that contract
    // instead of widening the generated client field to `any`.
    if (findField(schema, "\"oneOf\":")) |union_start| {
        if (parseArray(schema[union_start..])) |items| {
            const first = parseObject(items[1..]) orelse {
                try w.writeAll("unknown");
                return;
            };
            const rest = items[1 + first.len ..];
            const second = parseObject(rest) orelse {
                try w.writeAll("unknown");
                return;
            };
            try writeTsTypeFromJsonSchema(w, second);
            try w.writeAll(" | null");
            return;
        }
    }
    try w.writeAll("any");
}

// =========================================================================
// Mini JSON walker (we only need to inspect schemas we just wrote ourselves,
// so we can rely on the exact shape — no need for std.json.parseFromSlice).
// =========================================================================

/// Find the byte offset just after `key` (a quoted-string-with-colon, e.g.
/// `"properties":`). Returns null if not found at depth 0 of the containing
/// object.
fn findField(blob: []const u8, key: []const u8) ?usize {
    // Naive substring search at the top level. Since our schemas are
    // emitted by writeTypeSchema and are well-formed, this works without
    // a real JSON parser.
    var depth: i32 = 0;
    var i: usize = 0;
    while (i < blob.len) {
        const c = blob[i];
        if (c == '{') depth += 1;
        if (c == '}') depth -= 1;
        if (c == '"' and depth >= 0) {
            // Try matching key
            if (i + key.len <= blob.len and std.mem.eql(u8, blob[i .. i + key.len], key)) {
                if (depth == 1 or (depth == 0 and i == 0)) {
                    return i + key.len;
                }
            }
            // Skip string
            i += 1;
            while (i < blob.len and blob[i] != '"') {
                if (blob[i] == '\\') i += 1;
                i += 1;
            }
        }
        i += 1;
    }
    return null;
}

fn parseString(blob: []const u8) ?[]const u8 {
    var i: usize = 0;
    while (i < blob.len and blob[i] != '"') : (i += 1) {}
    if (i == blob.len) return null;
    const start = i + 1;
    i += 1;
    while (i < blob.len and blob[i] != '"') : (i += 1) {
        if (blob[i] == '\\') i += 1;
    }
    if (i == blob.len) return null;
    return blob[start..i];
}

fn parseObject(blob: []const u8) ?[]const u8 {
    var i: usize = 0;
    while (i < blob.len and blob[i] != '{') : (i += 1) {}
    if (i == blob.len) return null;
    const start = i;
    var depth: i32 = 0;
    while (i < blob.len) {
        if (blob[i] == '{') depth += 1;
        if (blob[i] == '}') {
            depth -= 1;
            if (depth == 0) return blob[start .. i + 1];
        }
        if (blob[i] == '"') {
            i += 1;
            while (i < blob.len and blob[i] != '"') {
                if (blob[i] == '\\') i += 1;
                i += 1;
            }
        }
        i += 1;
    }
    return null;
}

fn parseArray(blob: []const u8) ?[]const u8 {
    var i: usize = 0;
    while (i < blob.len and blob[i] != '[') : (i += 1) {}
    if (i == blob.len) return null;
    const start = i;
    var depth: i32 = 0;
    while (i < blob.len) {
        if (blob[i] == '[') depth += 1;
        if (blob[i] == ']') {
            depth -= 1;
            if (depth == 0) return blob[start .. i + 1];
        }
        i += 1;
    }
    return null;
}

fn arrayContainsString(arr: []const u8, needle: []const u8) bool {
    var i: usize = 0;
    while (i < arr.len) {
        if (arr[i] == '"') {
            const s = parseString(arr[i..]) orelse return false;
            if (std.mem.eql(u8, s, needle)) return true;
            i += s.len + 2;
            continue;
        }
        i += 1;
    }
    return false;
}

/// Walks `{ "foo": <value>, "bar": <value>, ... }`. Returns each (name,
/// value-slice) pair.
const ObjFieldIt = struct {
    blob: []const u8,
    pos: usize,

    const Pair = struct { name: []const u8, value: []const u8 };

    pub fn next(self: *ObjFieldIt) ?Pair {
        // Skip to next '"' that opens a key.
        while (self.pos < self.blob.len) {
            const c = self.blob[self.pos];
            if (c == '"') break;
            if (c == '}') return null;
            self.pos += 1;
        } else return null;
        const key = parseString(self.blob[self.pos..]) orelse return null;
        self.pos += key.len + 2; // skip "key"
        // skip ':' + whitespace
        while (self.pos < self.blob.len and self.blob[self.pos] != ':') : (self.pos += 1) {}
        self.pos += 1;
        while (self.pos < self.blob.len and (self.blob[self.pos] == ' ' or self.blob[self.pos] == '\t')) : (self.pos += 1) {}
        // value is either a string, number, object, array, true/false/null.
        const val_start = self.pos;
        const c = self.blob[self.pos];
        if (c == '{') {
            const v = parseObject(self.blob[self.pos..]) orelse return null;
            self.pos += v.len;
            return .{ .name = key, .value = v };
        }
        if (c == '[') {
            const v = parseArray(self.blob[self.pos..]) orelse return null;
            self.pos += v.len;
            return .{ .name = key, .value = v };
        }
        if (c == '"') {
            const v = parseString(self.blob[self.pos..]) orelse return null;
            self.pos += v.len + 2;
            return .{ .name = key, .value = self.blob[val_start .. val_start + v.len + 2] };
        }
        // bare token (number / bool / null)
        while (self.pos < self.blob.len and self.blob[self.pos] != ',' and self.blob[self.pos] != '}') : (self.pos += 1) {}
        return .{ .name = key, .value = self.blob[val_start..self.pos] };
    }
};

fn objectFieldsIterator(obj: []const u8) ObjFieldIt {
    // obj starts with '{'.
    return .{ .blob = obj, .pos = 1 };
}

/// Format adapter that writes a JSON string literal.
fn jsonString(s: []const u8) JsonStringFormatter {
    return .{ .s = s };
}

const JsonStringFormatter = struct {
    s: []const u8,
    pub fn format(self: JsonStringFormatter, w: *std.Io.Writer) std.Io.Writer.Error!void {
        try w.writeByte('"');
        for (self.s) |c| switch (c) {
            '"' => try w.writeAll("\\\""),
            '\\' => try w.writeAll("\\\\"),
            '\n' => try w.writeAll("\\n"),
            else => try w.writeByte(c),
        };
        try w.writeByte('"');
    }
};

test "operation names remain identifiers for artifact and wildcard routes" {
    var writer: std.Io.Writer.Allocating = .init(std.testing.allocator);
    defer writer.deinit();
    try writeOperationFnName(&writer.writer, .GET, "/openapi.json");
    try std.testing.expectEqualStrings("getOpenapiJson", writer.written());
    writer.clearRetainingCapacity();
    try writeOperationFnName(&writer.writer, .GET, "/users/:id/files/*key");
    try std.testing.expectEqualStrings("getUsersByIdFilesKey", writer.written());
}
