//! Lightweight realtime/embedded client generation from one Zig tagged union.
const reflection = @import("reflection.zig");
const std = @import("std");
const events = @import("events.zig");

pub const Target = enum { typescript, c };
pub const Options = struct { target: Target, name: []const u8 = "AkamataEvent", version: u16 = 1 };

/// Prefer the existing Protocol as the version/type source of truth. The
/// original union-based generate API remains available for compatibility.
pub fn generateProtocol(comptime Protocol: type, allocator: std.mem.Allocator, options: struct { target: Target, name: []const u8 = "AkamataEvent" }) ![]u8 {
    return generate(Protocol.Events, allocator, .{ .target = options.target, .name = options.name, .version = Protocol.protocol_version });
}

pub fn generate(comptime EventUnion: type, allocator: std.mem.Allocator, options: Options) ![]u8 {
    events.validateProtocol(EventUnion);
    var aw: std.Io.Writer.Allocating = .init(allocator);
    errdefer aw.deinit();
    switch (options.target) {
        .typescript => try emitTypescript(EventUnion, &aw.writer, options),
        .c => try emitC(EventUnion, &aw.writer, options),
    }
    return aw.toOwnedSlice();
}

fn emitTypescript(comptime U: type, w: *std.Io.Writer, options: Options) !void {
    try w.writeAll("// Generated by Akamata. Do not edit.\n");
    inline for (reflection.fields(@typeInfo(U).@"union")) |field| {
        try w.print("export interface {s}Payload ", .{title(field.name)});
        try writeTsType(field.type, w);
        try w.writeAll("\n");
    }
    try w.print("export type {s} =\n", .{options.name});
    inline for (reflection.fields(@typeInfo(U).@"union"), 0..) |field, i| {
        try w.print("  {s} {{ event_type: \"{s}\"; payload: {s}Payload }}\n", .{ if (i == 0) "=" else "|", field.name, title(field.name) });
    }
    // events.Protocol uses a flat wire envelope: the discriminator and payload
    // are siblings of the version/correlation metadata, not nested in `event`.
    try w.print("export interface AkamataEnvelopeMeta {{ protocol_version: {d}; event_id?: string; correlation_id?: string }}\n", .{options.version});
    try w.print("export type AkamataEnvelope = AkamataEnvelopeMeta & {s}\n", .{options.name});
    try w.writeAll(
        "export function connectAkamata(url: string, onEvent: (event: AkamataEnvelope) => void): WebSocket {\n" ++
            "  const ws = new WebSocket(url); ws.addEventListener(\"message\", e => onEvent(JSON.parse(String(e.data)))); return ws;\n}\n",
    );
}

fn emitC(comptime U: type, w: *std.Io.Writer, options: Options) !void {
    try w.writeAll("/* Generated by Akamata. Types and protocol metadata only. */\n#pragma once\n#include <stdint.h>\n#include <stddef.h>\n");
    try w.print("#define AKAMATA_PROTOCOL_VERSION {d}\n", .{options.version});
    try w.writeAll("typedef enum akamata_event_kind {\n");
    inline for (reflection.fields(@typeInfo(U).@"union"), 0..) |field, i| {
        try w.writeAll("  AKAMATA_EVENT_");
        try writeUpper(field.name, w);
        try w.print(" = {d},\n", .{i});
    }
    try w.writeAll("} akamata_event_kind;\n");
    inline for (reflection.fields(@typeInfo(U).@"union")) |field| {
        if (@typeInfo(field.type) != .@"struct") continue;
        try w.print("typedef struct akamata_{s}_payload {{\n", .{field.name});
        inline for (reflection.fields(@typeInfo(field.type).@"struct")) |member| {
            try writeCField(member.type, member.name, w);
        }
        try w.print("}} akamata_{s}_payload;\n", .{field.name});
    }
    try w.writeAll("typedef union akamata_event_payload {\n");
    inline for (reflection.fields(@typeInfo(U).@"union")) |field| {
        if (@typeInfo(field.type) == .@"struct") try w.print("  akamata_{s}_payload {s};\n", .{ field.name, field.name });
    }
    try w.writeAll("} akamata_event_payload;\n");
    try w.writeAll("typedef struct akamata_envelope_meta { uint16_t protocol_version; akamata_event_kind event_type; const char *event_id; const char *correlation_id; } akamata_envelope_meta;\n");
    try w.writeAll("typedef struct akamata_event { akamata_envelope_meta meta; akamata_event_payload payload; } akamata_event;\n");
}

fn writeTsType(comptime T: type, w: *std.Io.Writer) !void {
    if (@typeInfo(T) == .@"struct" and @hasDecl(T, "contract_kind")) {
        switch (T.contract_kind) {
            .bounded_string => try w.writeAll("string"),
            .fixed_bytes => try w.writeAll("number[]"),
            .bounded_slice => {
                try writeTsType(T.Element, w);
                try w.writeAll("[]");
            },
            else => unreachable,
        }
        return;
    }
    switch (@typeInfo(T)) {
        .@"struct" => |s| {
            try w.writeAll("{");
            inline for (reflection.fields(s)) |field| {
                try w.print(" {s}: ", .{field.name});
                try writeTsType(field.type, w);
                try w.writeAll(";");
            }
            try w.writeAll(" }");
        },
        .int, .float => try w.writeAll("number"),
        .bool => try w.writeAll("boolean"),
        .@"enum" => |e| inline for (reflection.fields(e), 0..) |field, i| try w.print("{s}\"{s}\"", .{ if (i == 0) "" else " | ", field.name }),
        .pointer => |p| if (p.size == .slice and p.child == u8) try w.writeAll("string") else try w.writeAll("unknown[]"),
        .array => try w.writeAll("number[]"),
        .optional => |o| {
            try writeTsType(o.child, w);
            try w.writeAll(" | null");
        },
        else => try w.writeAll("unknown"),
    }
}

fn writeCField(comptime T: type, comptime name: []const u8, w: *std.Io.Writer) !void {
    if (@typeInfo(T) == .@"struct" and @hasDecl(T, "contract_kind")) {
        switch (T.contract_kind) {
            .fixed_bytes => try w.print("  uint8_t {s}[{d}]; /* fixed length */\n", .{ name, T.max_len }),
            .bounded_string => try w.print("  char {s}[{d}]; uint16_t {s}_len; /* max {d} bytes */\n", .{ name, T.max_len, name, T.max_len }),
            .bounded_slice => {
                try w.writeAll("  ");
                try writeCScalar(T.Element, w);
                try w.print(" {s}[{d}]; uint16_t {s}_len; /* max {d} elements */\n", .{ name, T.max_len, name, T.max_len });
            },
            else => unreachable,
        }
        return;
    }
    switch (@typeInfo(T)) {
        .int => |i| try w.print("  {s}{d}_t {s};\n", .{ if (i.signedness == .signed) "int" else "uint", normalizedBits(i.bits), name }),
        .float => |f| try w.print("  {s} {s};\n", .{ if (f.bits <= 32) "float" else "double", name }),
        .bool => try w.print("  uint8_t {s};\n", .{name}),
        .array => |a| if (a.child == u8) try w.print("  uint8_t {s}[{d}];\n", .{ name, a.len }) else try w.print("  /* unsupported array element */ uint8_t {s}[{d}];\n", .{ name, a.len }),
        .pointer => |p| if (p.size == .slice and p.child == u8) try w.print("  const char *{s}; size_t {s}_len;\n", .{ name, name }) else try w.print("  /* unsupported pointer: {s} */ void *{s};\n", .{ @typeName(T), name }),
        .@"enum" => |e| {
            try w.print("  int32_t {s}; /* ", .{name});
            inline for (reflection.fields(e), 0..) |field, i| try w.print("{s}{s}={d}", .{ if (i == 0) "" else ", ", field.name, field.value });
            try w.writeAll(" */\n");
        },
        .optional => |o| {
            try w.print("  uint8_t {s}_present;\n", .{name});
            try writeCField(o.child, name, w);
        },
        else => try w.print("  /* unsupported field type: {s} */ uint8_t {s};\n", .{ @typeName(T), name }),
    }
}

fn writeCScalar(comptime T: type, w: *std.Io.Writer) !void {
    switch (@typeInfo(T)) {
        .int => |i| try w.print("{s}{d}_t", .{ if (i.signedness == .signed) "int" else "uint", normalizedBits(i.bits) }),
        .float => |f| try w.writeAll(if (f.bits <= 32) "float" else "double"),
        .bool => try w.writeAll("uint8_t"),
        .@"enum" => try w.writeAll("int32_t"),
        else => @compileError("bounded C slices require a scalar element type, got " ++ @typeName(T)),
    }
}

fn normalizedBits(bits: u16) u16 {
    return if (bits <= 8) 8 else if (bits <= 16) 16 else if (bits <= 32) 32 else 64;
}
fn title(comptime value: []const u8) []const u8 {
    return value;
}
fn writeUpper(value: []const u8, w: *std.Io.Writer) !void {
    for (value) |byte| try w.writeByte(std.ascii.toUpper(byte));
}

test "generate TypeScript and C realtime clients" {
    const E = union(enum) { created: struct { id: u64, name: []const u8 }, closed: struct { code: u16 } };
    const ts = try generate(E, std.testing.allocator, .{ .target = .typescript, .version = 2 });
    defer std.testing.allocator.free(ts);
    try std.testing.expect(std.mem.indexOf(u8, ts, "event_type: \"created\"") != null);
    try std.testing.expect(std.mem.indexOf(u8, ts, "AkamataEnvelopeMeta & AkamataEvent") != null);
    try std.testing.expect(std.mem.indexOf(u8, ts, "event: T") == null);
    const c = try generate(E, std.testing.allocator, .{ .target = .c, .version = 2 });
    defer std.testing.allocator.free(c);
    try std.testing.expect(std.mem.indexOf(u8, c, "AKAMATA_PROTOCOL_VERSION 2") != null);
    try std.testing.expect(std.mem.indexOf(u8, c, "AKAMATA_EVENT_CREATED") != null);
}

test "C generator preserves embedded bounds without heap metadata" {
    const bounded = @import("contract/bounded.zig");
    const E = union(enum) { report: struct {
        sequence: u32,
        name: bounded.BoundedString(64),
        digest: bounded.FixedBytes(32),
        samples: bounded.BoundedSlice(u16, 8),
        error_code: ?u16,
    } };
    const c = try generate(E, std.testing.allocator, .{ .target = .c, .version = 3 });
    defer std.testing.allocator.free(c);
    try std.testing.expect(std.mem.indexOf(u8, c, "uint32_t sequence") != null);
    try std.testing.expect(std.mem.indexOf(u8, c, "char name[64]") != null);
    try std.testing.expect(std.mem.indexOf(u8, c, "uint8_t digest[32]") != null);
    try std.testing.expect(std.mem.indexOf(u8, c, "uint16_t samples[8]") != null);
    try std.testing.expect(std.mem.indexOf(u8, c, "error_code_present") != null);
}
